<?php

require_once 'C:\xampp\htdocs\ValidEmail\ValidEmail.cl.php';

/**
 * Test class for ValidEmail.
 * Generated by PHPUnit on 2012-02-21 at 10:25:35.
 */
class ValidEmailTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ValidEmail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ValidEmail;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ValidEmail::setAddress
     * @dataProvider testSetAddressDataProvider
     */
    public function testSetAddress($address, $expectedResult)
    {
    	$this->assertEquals($this->object->setAddress($address), $expectedResult);
    }

    public function testSetAddressDataProvider()
    {
    	return array (
    		array ('"Abc@def"@example.com',true),
    		array ('Abc\@def@example.com',true),
	    	array ("dclo@us.ibm.com",true),
	    	array ("abc\\@def@example.com",true),
	    	array ("abc\\\\@example.com",true),
	    	array ("Fred\\ Bloggs@example.com",true),
	    	array ("Joe.\\\\Blow@example.com",true),
	    	array ("\"Abc@def\"@example.com",true),
	    	array ("\"Fred Bloggs\"@example.com",true),
	    	array ("customer/department=shipping@example.com",true),
	    	array ("\$A12345@example.com",true),
	    	array ("!def!xyz%abc@example.com",true),
	    	array ("_somename@example.com",true),
	    	array ("user+mailbox@example.com",true),
	    	array ("peter.piper@example.com",true),
	    	array ("Doug\\ \\\"Ace\\\"\\ Lovell@example.com",true),
	    	array ("\"Doug \\\"Ace\\\" L.\"@example.com",true),
	    	array ("abc@def@example.com",false),
	    	array ("abc\\\\@def@example.com",false),
	    	array ("abc\\@example.com",false),
	    	array ("@example.com",false),
	    	array ("doug@",false),
	    	array ("\"qu@example.com",false),
	    	array ("ote\"@example.com",false),
	    	array (".dot@example.com",false),
	    	array ("dot.@example.com",false),
	    	array ("two..dot@example.com",false),
	    	array ("\"Doug \"Ace\" L.\"@example.com",false),
	    	array ("Doug\\ \\\"Ace\\\"\\ L\\.@example.com",false),
	    	array ("hello world@example.com",false),
	    	array ("gatsby@f.sc.ot.t.f.i.tzg.era.l.d.",false)
    	);
    }
}
?>
