<?php

require_once 'C:\xampp\htdocs\ValidEmail\ValidEmail.cl.php';

/**
 * Test class for ValidEmail.
 * Generated by PHPUnit on 2012-02-21 at 10:25:35.
 */
class ValidEmailTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ValidEmail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ValidEmail;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ValidEmail::getAddress
     * @todo Implement testGetAddress().
     */
    public function testGetAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ValidEmail::setAddress
     * @todo Implement testSetAddress().
     */
    public function testSetAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
